service:
  hh_service:
    service:
      robot_description: /hh/robot_description
      end_effector: hh_link_ee
      fk_service_name: iiwa_fk_server
      ik_service_name: iiwa_ik_server
      jacobian_service_name: iiwa_jacobian_server
      jacobian_deriv_service_name: iiwa_jacobian_deriv_server
      jacobians_service_name: iiwa_jacobians_server
      gravity_service_name: iiwa_gravity_server